apiVersion: 1

datasources:
  - name: prometheus
    uid: ef50vzkc6tn28e
    type: prometheus
    access: proxy
    url: http://homechef-ops-prometheus:9090
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations: []
      httpMethod: POST
      pdcInjected: false
      prometheusType: Prometheus
      queryTimeout: 10s
      timeInterval: 10s
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://homechef-ops-loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
