global:
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - homechef-ops-prometheus:9090
  - job_name: node
    static_configs:
      - targets:
          - homechef-ops-prometheus-node-exporter:9100
  - job_name: homechef-core
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8000
  - job_name: postgres
    static_configs:
      - targets:
          - homechef-datastore-core-exporter:9187
  - job_name: redis
    static_configs:
      - targets:
          - homechef-cache-core-exporter:9121

