
services:
  homechef-ops-grafana:
    image: grafana/grafana:latest
    container_name: homechef-ops-grafana
    restart: unless-stopped
    ports:
      - '9990:3000'
    volumes:
      - './config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro'
      - './config/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro'
      - './config/grafana/dashboards:/etc/grafana/dashboards:ro'
      - './data/grafana-storage:/var/lib/grafana'
    networks: [ 'homechef-net' ]
    labels:
      - loki_scope=infra
    profiles: [ 'ops', 'full' ]

  homechef-ops-loki:
    image: grafana/loki:latest
    container_name: homechef-ops-loki
    ports:
      - "9993:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks: [ 'homechef-net' ]
    labels:
      - loki_scope=infra
    profiles: [ 'ops', 'full' ]

  homechef-ops-promtail:
    image: grafana/promtail:latest
    container_name: homechef-ops-loki-promtail
    volumes:
      - './config/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/var/log:/var/log:ro'
    command: -config.file=/etc/promtail/promtail-config.yml
    networks: [ 'homechef-net' ]
    labels:
      - loki_scope=infra
    profiles: [ 'ops', 'full' ]

  homechef-ops-prom-prometheus:
    image: prom/prometheus:latest
    container_name: homechef-ops-prometheus
    restart: unless-stopped
    ports:
      - '9991:9090'
    volumes:
      - './config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - './data/prometheus:/prometheus'
    networks: [ 'homechef-net' ]
    labels:
      - loki_scope=infra
    profiles: [ 'ops', 'full' ]

  homechef-ops-prom-node-exporter:
    image: prom/node-exporter:latest
    container_name: homechef-ops-prometheus-node-exporter
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - '9992:9100'
    networks: [ 'homechef-net' ]
    labels:
      - loki_scope=infra
    profiles: [ 'ops', 'full' ]

  homechef-log-tester:
    image: alpine:3.20
    container_name: homechef-ops-log-tester
    command: >
      sh -c '
        i=0;
        while true; do
          echo "$(date -Iseconds) level=INFO service=log-tester msg=\"hello from log-tester\" count=$i";
          i=$((i+1));
          sleep 2;
        done
      '
    restart: unless-stopped
    networks: [ 'homechef-net' ]
    labels:
      - loki_scope=infra
    profiles: [ 'ops', 'full' ]

  homechef-datastore-core:
    container_name: homechef-datastore-core
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks: [ 'homechef-net' ]
    ports:
      - "5432:5432"
    labels:
      - loki_scope=app
    profiles: [ 'db', 'full', 'app' ]

  homechef-datastore-core-exporter:
    container_name: homechef-datastore-core-exporter
    image: prometheuscommunity/postgres-exporter:latest
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@homechef-datastore-core:5432/core?sslmode=disable"
    ports:
      - "9187:9187"
    networks: [ 'homechef-net' ]
    labels:
      - loki_scope=infra
    depends_on:
      homechef-datastore-core:
        condition: service_healthy
    profiles: [ 'db', 'full', 'app' ]

  homechef-cache-core:
    container_name: homechef-cache-core
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"
    networks: [ 'homechef-net' ]
    labels:
      - loki_scope=app
    profiles: [ 'db', 'full', 'app' ]

  homechef-cache-core-exporter:
    container_name: homechef-cache-core-exporter
    image: oliver006/redis_exporter:latest
    restart: unless-stopped
    environment:
      REDIS_ADDR: "redis://homechef-cache-core:6379"
    ports:
      - "9121:9121"
    networks: [ 'homechef-net' ]
    labels:
      - loki_scope=infra
    depends_on:
      homechef-cache-core:
        condition: service_healthy
    profiles: [ 'db', 'full', 'app' ]

networks:
  homechef-net:
    driver: bridge

